import { Component } from '@angular/core';
import {
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonButton,
  IonItem,
  IonLabel,
  IonInput,
  IonCheckbox,
  IonRadio,
  IonRadioGroup,
  IonToggle,
  IonSelect,
  IonSelectOption,
  IonCard,
  IonCardHeader,
  IonCardTitle,
  IonCardContent,
  IonList,
  IonBadge,
  IonProgressBar,
  IonSpinner,
  IonRange,
  IonTextarea,
  IonChip,
  IonAvatar,
  IonIcon,
  IonGrid,
  IonRow,
  IonCol
} from '@ionic/angular/standalone';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
  standalone: true,
  imports: [
    IonHeader,
    IonToolbar,
    IonTitle,
    IonContent,
    IonButton,
    IonItem,
    IonLabel,
    IonInput,
    IonCheckbox,
    IonRadio,
    IonRadioGroup,
    IonToggle,
    IonSelect,
    IonSelectOption,
    IonCard,
    IonCardHeader,
    IonCardTitle,
    IonCardContent,
    IonList,
    IonBadge,
    IonProgressBar,
    IonSpinner,
    IonRange,
    IonTextarea,
    IonChip,
    IonAvatar,
    IonIcon,
    IonGrid,
    IonRow,
    IonCol
  ],
})
export class HomePage {
  constructor() {}
}